FROM php:7.2.3-fpm

RUN apt-get update && \
    apt-get install -y libmcrypt-dev && \
    #mariadb-client && \
    default-mysql-client && \
    #libmcrypt-dev && \
    pecl install mcrypt-1.0.2 && \
    docker-php-ext-enable mcrypt && \
    #zlib-bin && \
    #libfreetype6-dev && \
    #libjpeg62-turbo-dev && \
    #libpng-dev && \
    #docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install pdo_msql

WORKDIR "/app"
