version: "3"

services:
  vault:
    container_name: vault
    image: vault
    restart: "no"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/:/vault/config
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      SKIP_SETCAP: 1
